spring:
  application:
    name: helpdesk
    #NeonDB configurations
  datasource:
    url: ${NEON_DB}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  ai:
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        options:
#          model: phi4-mini:3.8b
#          temperature: 0.7
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
      client:
        enabled: true
    google:
      genai:
        api-key: ${GOOGLE_API_KEY}
        chat:
            options:
                model: gemini-3.5-flash
                temperature: 0.7

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG